version: '3.7'
services:
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - alertmanager-data:/alertmanager
    environment:
      - ALERTMANAGER_CONFIG_FILE=/alertmanager/config.yml
    command:
      - --config.file=/alertmanager/config.yml
volumes:
  alertmanager-data:
