global:
  resolve_timeout: 5m
  route:
    group_by: ['alertname']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
    receiver: 'monitoring'

receivers:
- name: 'monitoring'
  webhook_configs:
  - url: 'http://monitoring:9093/api/v1/alerts'
