server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
- url: http://logging:3100/loki/api/v1/push

scrapers:
- labels:
    job: varlog
  static_configs:
  - targets:
    - /var/log/*.log
